import type { Metadata } from "next";
import Link from "next/link";
import { Section, Eyebrow } from "@/components/site/section";
import { site } from "@/lib/site";
import { ScaleIcon } from "lucide-react";

export const metadata: Metadata = {
  title: "Privacy Policy | Camel Cement",
  description:
    "How Camel Cement collects, uses, stores and protects information submitted through the website, forms, quotations, orders, career applications and the Camel Build Assistant.",
};

const sections: { id?: string; heading: string; paragraphs: string[] }[] = [
  {
    heading: "Information We Collect",
    paragraphs: [
      "We collect the information you choose to provide through the website, such as your name, company, email address, phone number, region, district, project details and message content submitted through contact, quotation, order and career forms.",
      "We also collect limited technical information generated by your visit, such as pages viewed and general usage patterns, which helps us keep the website working correctly and improve its content.",
    ],
  },
  {
    heading: "How Information Is Used",
    paragraphs: [
      "Information submitted through forms is used to respond to your enquiry, prepare quotations, process order requests, provide dealer and product guidance and manage career applications.",
      "We may also use information to improve our products, services, website content and customer support processes. We do not sell personal information.",
    ],
  },
  {
    heading: "Legal Basis and Consent",
    paragraphs: [
      "We process personal information to respond to requests you make, to perform steps you ask us to take before entering a commercial relationship and, where required, on the basis of your consent.",
      "Where a form includes a consent checkbox, submitting the form with that box ticked records your agreement to the described use. You may withdraw consent by contacting us using the details below.",
    ],
  },
  {
    id: "cookies",
    heading: "Cookies and Analytics",
    paragraphs: [
      "The website uses cookies and similar technologies to support essential functions such as session handling, security and remembering your preferences.",
      "Where analytics tools are used, they help us understand how visitors use the website so we can improve navigation, content and performance. You can control cookies through your browser settings, although disabling some cookies may affect how parts of the website work.",
    ],
  },
  {
    heading: "AI Assistant Conversations",
    paragraphs: [
      "The Camel Build Assistant is provided to help you compare products, estimate materials, find dealers and prepare quotation requests.",
      "Messages you send to the assistant may be processed by our service providers to generate responses and may be reviewed to improve answer quality and safety. Do not share sensitive personal information in assistant conversations.",
    ],
  },
  {
    heading: "Career Application Data",
    paragraphs: [
      "Information submitted through career forms and the talent community, such as your name, contact details, areas of interest and any documents you provide, is used to assess your suitability for current or future roles.",
      "Access to this information is limited to people involved in recruitment and related administration.",
    ],
  },
  {
    heading: "File Uploads",
    paragraphs: [
      "Where the website allows file uploads, such as supporting documents for enquiries or applications, the files are used only for the purpose for which they were submitted.",
      "Please upload only documents that are relevant to your request and avoid including unnecessary personal information.",
    ],
  },
  {
    heading: "Data Retention",
    paragraphs: [
      "We keep personal information for as long as it is needed for the purpose it was collected, to maintain business records and to meet legal or regulatory requirements.",
      "When information is no longer required, we take steps to delete it or remove identifying details.",
    ],
  },
  {
    heading: "Data Security",
    paragraphs: [
      "We use reasonable technical and organisational measures designed to protect personal information against unauthorised access, loss and misuse.",
      "No method of transmission or storage can be guaranteed to be completely secure, so we encourage you to contact us if you have concerns about a specific submission.",
    ],
  },
  {
    heading: "Service Providers",
    paragraphs: [
      "We work with service providers that support the operation of this website, including hosting, database, analytics and AI services.",
      "These providers process information on our behalf under arrangements intended to protect it, and only to the extent needed to deliver their services.",
    ],
  },
  {
    heading: "Your Rights",
    paragraphs: [
      "Subject to applicable law, you may request access to the personal information we hold about you, ask for corrections, request deletion or object to certain uses.",
      "To exercise these rights, contact us using the details below. We may need to verify your identity before acting on a request.",
    ],
  },
  {
    heading: "Contact for Privacy Requests",
    paragraphs: [
      `For privacy questions or requests, contact Camel Cement at ${site.generalEmail} or call ${site.phone}. You can also write to ${site.postal}.`,
    ],
  },
  {
    heading: "Policy Updates",
    paragraphs: [
      "We may update this policy as our services, technology or legal obligations change. The updated version will be published on this page, and significant changes will be highlighted where practical.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <>
      <Section surface="canvas" className="border-b border-concrete-200">
        <div className="container-reading space-y-5">
          <Eyebrow>PRIVACY</Eyebrow>
          <h1 className="text-h1 text-balance text-concrete-950">
            Privacy Policy
          </h1>
        </div>
      </Section>

      <Section surface="white">
        <div className="container-reading space-y-10">
          <div className="flex items-start gap-3 rounded-xl border border-camel-yellow-200 bg-camel-yellow-50 p-5">
            <ScaleIcon
              className="mt-0.5 size-5 shrink-0 text-camel-yellow-700"
              aria-hidden="true"
            />
            <p className="text-sm font-semibold text-concrete-950">
              This page is prepared for legal review before production launch.
            </p>
          </div>

          <div className="space-y-5">
            <p className="text-xl font-bold text-concrete-950">
              Your privacy matters to us.
            </p>
            <p className="text-[17px] leading-[1.75] text-concrete-800">
              This page explains how Camel Cement collects, uses, stores and
              protects information submitted through website forms, quotation
              requests, orders, career applications, dealer searches, analytics
              and the Camel Build Assistant.
            </p>
          </div>

          {sections.map((section) => (
            <div
              key={section.heading}
              id={section.id}
              className="space-y-4 scroll-mt-24"
            >
              <h2 className="text-h3 text-concrete-950">{section.heading}</h2>
              {section.paragraphs.map((paragraph) => (
                <p
                  key={paragraph.slice(0, 32)}
                  className="text-[17px] leading-[1.75] text-concrete-800"
                >
                  {paragraph}
                </p>
              ))}
            </div>
          ))}

          <p className="border-t border-concrete-200 pt-6 text-sm text-concrete-600">
            See also the{" "}
            <Link
              href="/terms"
              className="font-bold text-camel-green-700 hover:underline"
            >
              website terms of use
            </Link>
            .
          </p>
        </div>
      </Section>
    </>
  );
}
